#!/bin/bash

# Guia de Início Rápido - Sistema de Loja Tkinter
# Tudo o que precisa em um script

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║                                                            ║"
echo "║   ⌂ SISTEMA DE LOJA DE INFORMÁTICA - VERSÃO TKINTER   ║"
echo "║                  GUIA DE INÍCIO RÁPIDO                    ║"
echo "║                                                            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "▨ O QUE VOCÊ PRECISA FAZER:"
echo "════════════════════════════════════════════════════════════"
echo ""

echo "[1]  ATIVAR AMBIENTE VIRTUAL"
echo "   $ cd /home/elgz/Documentos/Form_Prog_Python/Eng_Soft"
echo "   $ source venv/bin/activate"
echo ""

echo "[2]  SETUP ÚNICO (recomendado)"
echo "   $ python setup_completo.py"
echo ""
echo "   OU fazer cada passo:"
echo "   $ python migracao_admin.py"
echo "   $ python inserir_clientes_teste.py"
echo ""

echo "[3]  EXECUTAR A APLICAÇÃO"
echo "   $ python sistema_loja_tkinter.py"
echo ""

echo "════════════════════════════════════════════════════════════"
echo ""

echo "◩ DADOS DE TESTE:"
echo "════════════════════════════════════════════════════════════"
echo ""

echo "ADMINISTRADOR:"
echo "  Email: joao@example.com"
echo "  Password: user123"
echo "  ➜ Acesso completo ao painel de administrador"
echo ""

echo "UTILIZADORES:"
echo "  • maria@example.com / user123"
echo "  • pedro@example.com / user123"
echo "  • ana@example.com / user123"
echo "  • carlos@example.com / user123"
echo "  ➜ Acesso ao painel de cliente (explorar produtos, compras)"
echo ""

echo "════════════════════════════════════════════════════════════"
echo ""

echo "[STAR] FUNCIONALIDADES:"
echo "════════════════════════════════════════════════════════════"
echo ""

echo "▸  CLIENTE NORMAL:"
echo "  ✔ Login com email e password"
echo "  ✔ Explorar produtos disponíveis"
echo "  ✔ Adicionar produtos ao carrinho"
echo "  ✔ Ver carrinho com total"
echo "  ✔ Finalizar compra"
echo "  ✔ Logout"
echo ""

echo "▲ ADMINISTRADOR:"
echo "  ✔ Painel de admin com opções:"
echo "    - Gerir Produtos (ver inventário)"
echo "    - Gerir Clientes (ver lista de utilizadores)"
echo "    - Ver Vendas (histórico de compras)"
echo ""

echo "════════════════════════════════════════════════════════════"
echo ""

echo "◆ SEGURANÇA:"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "  • Passwords hasheadas com bcrypt (12 rounds)"
echo "  • Cada password tem seu próprio salt único"
echo "  • Validação real de login"
echo "  • Proteção contra SQL injection"
echo ""
echo "  TESTE: Tente login com password errada"
echo "  Resultado esperado: ✘ 'Password incorreta!'"
echo ""

echo "════════════════════════════════════════════════════════════"
echo ""

echo "▣ ESTATÍSTICAS ESPERADAS:"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "  • Clientes: 5 (1 admin + 4 utilizadores)"
echo "  • Produtos: 10 (artigos de informática)"
echo "  • Stock Total: 122 unidades"
echo ""

echo "════════════════════════════════════════════════════════════"
echo ""

echo "◐ DICAS:"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "  1. Se error BD: Certifique-se MariaDB está em execução"
echo "     $ /opt/lampp/bin/xampp start"
echo ""
echo "  2. Se password não funciona: Password padrão é 'user123'"
echo ""
echo "  3. Para adicionar novo cliente: Edite inserir_clientes_teste.py"
echo ""
echo "  4. Para mudar BD: Edite parametros em sistema_loja_tkinter.py"
echo ""
echo "  5. Tkinter é nativo - não precisa instalar nada extra!"
echo ""

echo "════════════════════════════════════════════════════════════"
echo ""

echo "[DOC] DOCUMENTAÇÃO:"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "  • GUIA_TKINTER.md - Documentação completa"
echo "  • RESUMO_TKINTER.txt - Sumário das mudanças"
echo "  • Esta pasta: /home/elgz/.../Eng_Soft/"
echo ""

echo "════════════════════════════════════════════════════════════"
echo ""

echo "◇ PRONTO!"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Pode começar agora:"
echo ""
echo "  source venv/bin/activate && python sistema_loja_tkinter.py"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
